baseURL: /
title: OMEGA
theme: omega-hugo
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - name: Home
      pre: ''
      url: /
      weight: 1
    - name: About
      pre: '#'
      url: mission
      weight: 2
    - name: Products
      pre: '#'
      url: products
      weight: 3
    - name: Career
      pre: ''
      url: career
      weight: 4
    - name: Contact
      pre: '#'
      url: contact
      weight: 5
params:
  author: Themefisher
  contact_info: 1001 Brickell bay <br>Dr. Miami, <br>FL 33131
  cookies:
    enable: yes
    expire_days: 2
  description: This is meta description
  logo: images/logo.png
  logo_width: 120px
  map:
    enable: yes
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw
    map_center_lat: '25.773606'
    map_center_lng: '-80.732655'
    map_marker: images/map-marker.png
    map_position_lat: '25.7635916'
    map_position_lng: '-80.1937595'
  preloader: yes
  social:
    - icon: fa-facebook
      link: '#'
      title: facebook
    - icon: fa-twitter
      link: '#'
      title: twitter
    - icon: fa-instagram
      link: '#'
      title: instagram
    - icon: fa-github
      link: '#'
      title: github
    - icon: fa-linkedin
      link: '#'
      title: linkedin
